### ISSUE TITLE
Create Navbar Component

### ISSUE THREAD

**Issue by Rashmil-1999** [IN-CORE/incore-studio#12]
According to design, we have 2 components, being used across the application, the Navbar and Sidebar where one is able to move around the webapp and perform actions.

**Comment by Rashmil-1999** [comment]
According to the new design, we no longer have the sidebar but instead a project sidebar. So it would be better to just have this issue as to create the Navbar component.
<img width="1761" alt="Screenshot 2024-09-30 at 9 13 39 AM" src="https://github.com/user-attachments/assets/f3fa79b9-8df0-4f42-906a-5b460ef880ec">

**Comment by Rashmil-1999** [comment]
<img width="202" alt="Screenshot 2024-10-23 at 2 38 11 PM" src="https://github.com/user-attachments/assets/5ec7af83-c036-4f29-bf80-1301a6a763fe">
So, we need to have logo of incore and the font and text color is a bit different. Could you please change that?

**Comment by Rashmil-1999** [comment]
if the app doesn't start, you may want to remove the extra "/" here https://github.com/IN-CORE/incore-studio/blob/94a99391bbe8418c9d526831b4c174809bc3aa59/src/App.tsx#L22

**Comment by ylyangtw** [comment]
> <img alt="Screenshot 2024-10-23 at 2 38 11 PM" width="202" src="https://private-user-images.githubusercontent.com/32737711/379438789-5ec7af83-c036-4f29-bf80-1301a6a763fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MTI5ODgsIm5iZiI6MTcyOTcxMjY4OCwicGF0aCI6Ii8zMjczNzcxMS8zNzk0Mzg3ODktNWVjN2FmODMtYzAzNi00ZjI5LWJmODAtMTMwMWE2YTc2M2ZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDE5NDQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyNGI0MzhiOWY3ZjM3MWQzM2YxYjhjY2E1NDIwMjZiMjc5MGNkY2VhY2FhNTVjMTc3M2M1YjZiZWNmYzcxZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Z-Sro44hIFees5wCZ_S6bNR_9ohvCAdzf1vZnuVLdsM"> So, we need to have logo of incore and the font and text color is a bit different. Could you please change that?

oh ok, I can work on this
