### ISSUE TITLE
Home need to redirect to subdirectory slash studio

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/incore-studio#74]
<img width="457" alt="image" src="https://github.com/user-attachments/assets/080ab8d4-c57d-43ce-9301-c4f210394166" />
Right now this is redirect at the root; need to be redirect to /studio

**Comment by longshuicy** [comment]
breakcrumb needs to be rewritten to append /studio in general

**Comment by Rashmil-1999** [comment]
Closing this as this has been fixed as a part of the nginx and link fixes.
